# Site settings
author: Doak Covington
title: Easy Money
header-img: img/home-bg.png
email: doakcovington@protonmail.com
copyright_name: Doak Covington
description: > # this means to ignore newlines until "baseurl:"
  A Difficult Career Change
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  doakcovington

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
